services:
  api:
    container_name: @PROJECT_NAME@-api
    restart: always
    env_file: api/.flaskenv
    build:
      context: api/.docker
      args:
        - APPUID=${UID}
        - APPUGID=${GID}
        - VIRTUAL_ENV=${PYTHON_VIRTUAL_ENV}
    environment:
      - PYTHONPATH=/api
      - PIPENV_DONT_LOAD_ENV=1
    depends_on:
      - db
    volumes:
      - ./api:/api
      - api-venv:/opt/venv
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.11.2
    extra_hosts:
      - "@PROJECT_NAME@-db:10.120.11.5"
  api_gateway:
    container_name: @PROJECT_NAME@-api-gateway
    restart: always
    image: "nginx"
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api-gateway/.docker/nginx:/etc/nginx/conf.d
      - ./api-gateway/.docker/etc/ssl:/etc/ssl
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.11.3
    depends_on:
      - api
    extra_hosts:
      - "api:10.120.11.2"
  web:
    container_name: @PROJECT_NAME@-web
    build:
      context: web/.docker
      target: dev #see in Dockerfile target
    volumes:
      - ./web:/web
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
#    ports:
#      - "3000"
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.11.4
  db:
    ports:
      - ${DB_PORT}:3306
    container_name: @PROJECT_NAME@-db
    volumes:
      - .docker/db/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - db-data:/var/lib/mysql
    build:
      context: .docker/db
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.11.5
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  api-venv: {}
  db-data: {} # docker will create volume in /var/lib/docker/volumes

networks:
  @PROJECT_NAME@:
    name: @PROJECT_NAME@
    driver: bridge
    ipam:
      config:
        - subnet: 10.120.11.0/24

# Entries should be placed in file /etc/hosts

# please add to /etc/hosts file

# 10.120.11.3 @PROJECT_NAME@-api
# 10.120.11.3 @PROJECT_NAME@-api.com

# 10.120.11.4 @PROJECT_NAME@-web
# 10.120.11.4 @PROJECT_NAME@-web.com

# 10.120.11.5 @PROJECT_NAME@-db

